import time
import webbrowser

print("Auto KRNL Enabled")
webbrowser.open_new_tab("https://cdn.krnl.place/getkey.php")
print("[LOGS] Redirect to 1 step. PRESS SUBMIT")
print("[LOGS] NexusPIPE detect wait to load uam and u complate captch. Press any key if u complete all")
input()
print("[LOGS] OK")
time.sleep(15)
print("[LOGS] Redirect to 2 step. And wait 15 sec. complate captch and PRESS SUBMIT. Press any key if u complete all")
webbrowser.open_new_tab("https://cdn.krnl.place/getkey_games")
input()
print("[LOGS] OK")
time.sleep(15)
print("[LOGS] Redirect to 3 step. And wait 15 sec. complate captch and PRESS SUBMIT. Press any key if u complete all")
webbrowser.open_new_tab("https://cdn.krnl.place/getkey_interface")
input()
print("[LOGS] OK")
time.sleep(15)
print("[LOGS] Redirect to 4 step. And wait 15 sec. complate captch and PRESS SUBMIT. Press any key if u complete all")
webbrowser.open_new_tab("https://cdn.krnl.place/getkey_scripts")
input()
print("[LOGS] OK")
time.sleep(15)
print("[LOGS] Redirect to 5 step.")
webbrowser.open_new_tab("https://cdn.krnl.place/getkey.php")
